app/routes.php
<?php
# Site /estaticas

//Route::get('sub', 'SubscriptionsController@showSubCount');
Route::get('/',['as'=>'home','uses'=>'SiteController@index']);
Route::get('como-functiona', ['as'=>'about', 'uses'=>'SiteController@about']);
Route::get('perguntas-frequentes', ['as'=>'faq', 'uses'=>'SiteController@faq']);
Route::get('termos-de-uso', ['as'=>'terms', 'uses'=>'SiteController@terms']);
Route::get('contato', ['as'=>'get.contact', 'uses'=>'SiteController@getContact']);
Route::post('contato', ['as'=>'post.contact', 'uses'=>'SiteController@postContact']);
Route::post('webhooks',['as'=>'webhooks','uses'=>'SiteController@webhooks']);

# Cadastro
Route::get('cadastro',['before'=>'already.logged','as'=>'auth.register', 'uses'=>'AuthController@register']);
Route::post('cadastro',['as'=>'auth.post.register', 'uses'=>'AuthController@postRegister']);
# Testedecriação de conta
Route::get('criar-conta/{user_id}/teste/{project_id}', 'SubscriptionsController@createAccount');

# Newslleters
Route::post('newsletters', ['as'=>'newsletter.store', 'uses'=>'NewslettersController@store']);
# Login
Route::get('login',['before'=>'already.logged','as'=>'auth.login', 'uses'=>'AuthController@login']);
Route::post('login',['as'=>'auth.post.login', 'uses'=>'AuthController@postLogin']);
# BUscas
Route::get('buscar',['as'=>'main.search', 'uses'=>'ProjectsController@search']);
# Passwords
Route::get('password/reset', ['uses' => 'PasswordController@remind',  'as' => 'password.remind']);
Route::post('password/reset', ['uses' => 'PasswordController@request', 'as' => 'password.request']);
Route::get('password/reset/{token}', ['uses' => 'PasswordController@reset', 'as' => 'password.reset']);
Route::post('password/reset/{token}', ['uses' => 'PasswordController@update', 'as' => 'password.update']);

# Projetos
Route::get('projetos',['as'=>'projects.index', 'uses'=>'ProjectsController@indexSite']);
Route::get('projeto/{slug}',['as'=>'project.show', 'uses'=>'ProjectsController@showSite']);

# Categorias
Route::get('projetos/{slug_cat}',['as'=>'category.show', 'uses'=>'ProjectsController@indexSite']);
# Buscas
Route::post('city/search', ['as'=>'city.search', 'uses'=>'CitiesController@searchByState']);
Route::post('city/search/name', ['as'=>'city.search.name', 'uses'=>'CitiesController@searchByStateName']);

	# Pratocinar / Kart
Route::group(['before'=>'auth|force.ssl'],function(){
	Route::get('projeto/{slug}/patrocinar',['as'=>'project.subscribe', 'uses'=>'SubscriptionsController@getSubscribe']);
	Route::post('projeto/{slug}/patrocinar',['as'=>'project.payment.subscribe', 'uses'=>'SubscriptionsController@paymentSubscribe']);

	Route::get('projeto/{slug}/patrocinar/checkout',['as'=>'project.subscribe.checkout', 'uses'=>'SubscriptionsController@getSubscribeCheckout']);
	Route::post('projeto/{slug}/patrocinar/checkout',['as'=>'project.post.subscribe', 'uses'=>'SubscriptionsController@postSubscribe']);
});

# Accounts
Route::group(['prefix'=>'minha-conta','before'=>'auth'],function(){
	# Tipagem
	Route::get('patrocinador', ['before'=>'already.producer','as'=>'user.account.sponsor', 'uses'=>'UsersController@profileSponsor']);
	Route::get('produtor', ['before'=>'has.producer', 'as'=>'user.account.producer', 'uses'=>'SubscriptionsController@profileProducer']);

	#Produtor
	Route::get('produtor/verificacao', ['as'=>'producer.create', 'uses'=>'UsersController@createProducer']);
	Route::post('produtor/verificacao', ['as'=>'producer.store', 'uses'=>'SubscriptionsController@createAccount']);
	// Enviando a verificação ao IUGU
	Route::get('produtor/{pid}/verificacao', ['as'=>'sending.verification', 'uses'=>'SubscriptionsController@sendindVerification']);

	# Update de senha
	Route::post('salvar/nova/senha',['as'=>'user.update.password', 'uses'=>'PasswordController@updatePass']);

	#Updae userdata
	Route::post('salvar/dados/usuario',['as'=>'user.update.userdata','uses'=>'UsersController@updateUserdata']);
	# Upload de imagem
	Route::post('image/upload', ['as'=>'user.upload.photo','uses'=>'UsersController@uploadImage']);

	# Projetos
	Route::get('projeto',['before'=>'has.producer','as'=>'projects.create', 'uses'=>'ProjectsController@createSite']);
	Route::post('projeto', ['before'=>'has.producer','as'=>'projects.store', 'uses'=>'ProjectsController@storeSite']);

	Route::group(['before'=>'my.project|has.producer', 'prefix'=>'projeto/{slug}'], function(){
		Route::get('editar',['as'=>'projects.edit', 'uses'=>'ProjectsController@editSite']);
		Route::post('editar', ['as'=>'projects.update', 'uses'=>'ProjectsController@updateSite']);

		# Projeto single(área admin)
		Route::get('/',['as'=>'projects.account.show', 'uses'=>'ProjectsController@accountShow']);

		# Criação de metas e recompensas
		Route::get('metas',['as'=>'project.objective.create', 'uses'=>'ProjectsController@objectiveCreate']);
		Route::post('metas',['as'=>'project.objective.store', 'uses'=>'ProjectsController@objectiveStore']);
		Route::delete('metas/{objective_id}',['as'=>'project.objective.delete', 'uses'=>'ProjectsController@objectiveDelete']);
		Route::get('recompensas',['as'=>'project.reward.create', 'uses'=>'ProjectsController@rewardCreate']);
		Route::post('recompensas',['as'=>'project.reward.store', 'uses'=>'SubscriptionsController@rewardStore']);
                Route::delete('recompensas/{reward_id}',['as'=>'project.reward.delete', 'uses'=>'ProjectsController@rewardDelete']);
	});

	# Cancelar subscriptiom
	Route::post('cancelar/{subscription_id}',['as'=>'subscription.cancel','uses'=>'SubscriptionsController@cancel']);
	#Logout
	Route::get('logout',['as'=>'user.logout', 'uses'=>'AuthController@logout']);

});
# Admin
Route::get('admin',['before'=>'already.logged.admin','as'=>'admin.login', 'uses'=>'AdminController@login']);
Route::post('admin/login',['as'=>'admin.post.login', 'uses'=>'AdminController@postLogin']);
Route::get('admin/logout',['as'=>'admin.logout', 'uses'=>'AdminController@logout']);

Route::group(['prefix'=>'admin', 'before'=>'auth|admin', 'namespace' => 'Admin'], function(){
    
    Route::resource('projetos', 'ProjectsController');
    Route::post('projeto/{id}/aprovar', ['as'=>'admin.projetos.aprovar', 'uses'=>'ProjectsController@aprovar']);
    Route::post('projeto/{id}/justifica', ['as'=>'admin.projetos.justifica', 'uses'=>'ProjectsController@justifica']);
    
    Route::resource('usuarios', 'UsersController');
    Route::post('usuario/{id}/ativacao', ['as'=>'admin.user.deactivate', 'uses'=>'UsersController@deactivate']);
        
    Route::resource('newsletters', 'NewslettersController');
    Route::post('news/download', ['as'=>'admin.newsletters.download', 'uses'=>'NewslettersController@download']);
    
    Route::resource('patrocinios', 'SubscriptionsController');
    Route::get('dashboard', ['as'=>'admin.dashboard.index', 'uses'=>'DashboardController@index']);
}); 

app/models/Project.php
<?php

use Illuminate\Database\Eloquent\SoftDeletingTrait;

class Project extends \Eloquent{
	
        use SoftDeletingTrait;
        
        protected $dates = ['deleted_at'];
	protected $fillable = ['name','site','excerpt','description','approval_comment'];

	public static $rules = [
		'name'=>'required', 
		'site'=>'required',
		'excerpt'=>'required|max:67',
		'description'=>'required',
		'category_id' => 'required'
	];

	public function categories()
	{
		return $this->belongsToMany('Category','projects_categories');
	}

	public function user()
	{
		return $this->belongsTo('User');
	}

	public function subscriptions()
	{
		return $this->hasMany('Subscription');
	}

	public function getAllCash()
	{
		
		$sum = Subscription::whereIn('id',$this->subscriptions->lists('id'))->sum('amount');
		
		return $sum/100;
	}

	public function objectives()
	{
		return $this->hasMany('Objective');
	}

	public function rewards()
	{
		return $this->hasMany('Reward');
	}
	public function scopeFeatured($query)
	{
		return $query->whereFeatured('1');
	}

	public function scopeActive($query)
	{
		return $query->where('status','1');
	}

	public function scopeConfirmed($query)
	{
		return $query->where('status_docs','1');
	}

	public function getVideo()
	{
		if($this->video_type == '1'){
			// youtube
			return '<iframe style="width:100%;" height="350" src="https://www.youtube.com/embed/'.$this->video_src.'" frameborder="0" allowfullscreen></iframe>';
		}elseif($this->video_type == '2'){
			return '<iframe src="https://player.vimeo.com/video/'.$this->video_src.'" style="width:100%;" height="350" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';
		}

		return null;
	}
	
	public function getImageSrc($size_path = 'uploads/thumbs/')
	{
		if($size_path == 'uploads/banner/'){
			return $this->image != '' ? asset($size_path.$this->image) : asset('img/project_default_banner.jpg'); 
		}
		return $this->image != '' ? asset($size_path.$this->image) : asset('img/project_default_image.jpg'); 
	}
}

app/controllers/Admin/ProjectsController.php
<?php

namespace Admin;

use \Project;
use \Category;
use \File;
use \Input;
use \View;
use \Validator;
use \Redirect;

class ProjectsController extends \BaseController {
    
    
    public function index() 
    {
        $p = Project::orderBy('id','desc');

        if(Input::has('n')){
            $p->where('name','like','%'.Input::get('n').'%');
        }

        $projects = $p->paginate(10);

        return View::make('admin2.projects.index', compact('projects'));
    }
    
    public function create(){
        return Redirect::route('admin.projetos.index')->withWarning('Ação não implementada');
    }
    
    public function store(){
        return Redirect::route('admin.projetos.index')->withWarning('Ação não implementada');
    }
    
    public function show($id) {
        return Redirect::route('admin.projetos.edit', $id);
    }
    
    public function edit($id)
    {
        $project = Project::find($id);
        $project->load('objectives');
        $project->load('rewards');
        $project_categories = $project->categories()->lists('category_id');
        $categories = [''=>'Escolher categoria'] + Category::orderBy('name')->lists('name','id');
        
        $networks = \Network::all();
	$n = $project->networks != '' ? unserialize(base64_decode($project->networks)) : array();
        
        return View::make('admin2.projects.edit', compact('categories','project','project_categories','networks','n'));
    }
    
    public function update($id)
    {
        $validator = Validator::make(Input::except('objectives','rewards'), \Project::$rules);
        $validatorObjectives = $this->setupObjectiveValidator();
        $validatorRewards = $this->setupRewardValidator();

        if ($validator->fails() || $validatorObjectives->fails() || $validatorRewards->fails()) 
        {
            $errors = $validator->messages()
                ->merge($validatorObjectives->messages())
                ->merge($validatorRewards->messages())
            ;
             
            return Redirect::route('admin.projetos.edit', $id)
                ->withErrors($errors)
                ->withInput(\Input::except('password'))
            ;
            
        } else {

            $p = Project::find($id);
            $p->name = Input::get('name');
            $p->excerpt = Input::get('excerpt');
            $p->description = Input::get('description');
            $p->featured = Input::get('featured');
            $p->status = Input::get('status');
            $p->site = Input::get('site');
            $p->networks = !empty(Input::get('networks')) ? base64_encode(serialize(Input::get('networks'))) : null;
            $p->categories()->sync(array_values(Input::get('category_id')));
            
            $video = $this->processVideo();
            
            $p->video_src = $video['video_src'];
            $p->video_link = $video['video_link'];
            $p->video_type = $video['video_type'];
                        
            if(Input::hasFile('image'))
            {
                if($p->image != ''){
                    File::delete('uploads/normal/'.$p->image);
                    File::delete('uploads/thumbs/'.$p->image);
                    File::delete('uploads/banner/'.$p->image);
                }
                
                $p->image = $this->upload_file(Input::file('image'), true);
            }
            
            if(Input::has('objectives'))
            {
                foreach(Input::get('objectives') as $i => $params) 
                {
                    $objective = \Objective::findOrNew($params['id']);
                    if(isset($params['delete']) && !is_null($objective->id)) {
                        $objective->delete();
                    } else {
                        $objective->value = \Helper::toCents($params['value']);
                        $objective->name = $params['name'];
                        $objective->result = $params['result'];
                        $objective->project()->associate($p);
                        $objective->save();
                    }
                }
            }
            
            if(Input::has('rewards'))
            {
                foreach(Input::get('rewards') as $i => $params) 
                {
                    $reward = \Reward::findOrNew($params['id']);
                    if(isset($params['delete']) && !is_null($reward->id)) {
                        $reward->delete();
                    } else {
                        $reward->value = \Helper::toCents($params['value']);
                        $reward->title = $params['title'];
                        $reward->description = $params['description'];
                        $reward->project()->associate($p);
                        $reward->save();
                    }
                }
            }
            
            $p->push();
            
            return Redirect::route('admin.projetos.index')->withSuccess('Projeto atualizado com sucesso');
        }  
        
    }
    
    public function destroy($id){
        $project = Project::find($id);
        $project->delete();
        
        //Cancelar inscrições
        
        return Redirect::route('admin.projetos.index')->withSuccess('Projeto removido com sucesso');
    }
    
    public function aprovar($id)
    {
        $project = Project::find($id);
	$project->status = Input::get('state') == 'true' ? '1' : '0';
	$project->save();
	$res = Input::get('state') == 'true' ? 'Projeto ativado com sucesso' : 'Projeto reprovado';
	return Response::json(['response'=>$res,'status'=>Input::get('state')]);
    }

    public function justifica($id)
    {
        $project = Project::find($id);
	$project->approval_comment = Input::get('approval_comment');
	$project->save();

	Mail::send('emails.projects.justify', ['project'=>$project], function($m) use($project){
            $m->to($project->user->email, $project->user->name)->subject('Bepartus - Saiba porque seu projeto não foi aprovado');
	});
	return Redirect::route('admin.projetos.index', Input::get('page', null))->withSuccess('Justificativa enviada com sucesso!');
    }
    
    private function setupObjectiveValidator() 
    {
        $objectives = Input::get('objectives');
        $objectivesRules = [];
        $objectivesAttrNames = [];
        
        if(Input::has('objectives'))
        {
            foreach( $objectives as $i => $obj ) {
                $objectivesRules['objectives.'.$i.'.value'] = 'required|greaterthan:0';
                $objectivesRules['objectives.'.$i.'.name'] = 'required|max:255';
                $objectivesRules['objectives.'.$i.'.result'] = 'required';

                $objectivesAttrNames['objectives.'.$i.'.value'] = 'Valor';
                $objectivesAttrNames['objectives.'.$i.'.name'] = 'Nome';
                $objectivesAttrNames['objectives.'.$i.'.result'] = 'Resultado';
            }
        }

        $validatorObjectives = Validator::make(Input::only('objectives'), $objectivesRules);
        $validatorObjectives->setAttributeNames($objectivesAttrNames); 
        
        return $validatorObjectives;
    }
    
    private function setupRewardValidator() 
    {
        $rewards = Input::get('rewards');
        $rewardsRules = [];
        $rewardsAttrNames = [];
        
        if(Input::has('rewards'))
        {
            foreach( $rewards as $i => $obj ) {
                $rewardsRules['rewards.'.$i.'.value'] = 'required|greaterthan:0';
                $rewardsRules['rewards.'.$i.'.title'] = 'required|max:255';
                $rewardsRules['rewards.'.$i.'.description'] = 'required';

                $rewardsAttrNames['rewards.'.$i.'.value'] = 'Valor';
                $rewardsAttrNames['rewards.'.$i.'.title'] = 'Titulo';
                $rewardsAttrNames['rewards.'.$i.'.description'] = 'Descrição';
            }
        }

        $validatorRewards = Validator::make(Input::only('rewards'), $rewardsRules);
        $validatorRewards->setAttributeNames($rewardsAttrNames); 
        
        return $validatorRewards;
    }
    
    private function processVideo() 
    {
        $data = Input::all();
        $video_src = null;
        $video_type = '0';

        if(Input::has('video_src'))
        {
            if(strpos($data['video_src'], 'yout')){
                $video_src = \Helper::parse_youtube($data['video_src']);
		$video_type = '1';
            } elseif(strpos($data['video_src'], 'vimeo')) {
                $video_src = \Helper::parse_vimeo($data['video_src']);
		$video_type = '2';
            } else {
                $video_src = null;
		$video_type = '0';
            }
        }
        
        return [
            'video_src' => $video_src,
            'video_link' => $data['video_src'] != '' ? $data['video_src'] : '',
            'video_type' => $video_type
        ];  
    }
}

app/views/admin/projects/index.blade.php
@extends('layouts.admin')
@section('content')
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Projetos <small>({{ $projects->getTotal() }})</small>
        </h1>
    </div>
</div>
<div class="row">
	<div class="col-md-12">
		{{ Form::open(['route'=>'admin.projetos.index', 'method'=>'get', 'class'=>'form-inline']) }}
		{{ Form::text('n', Input::get('n'), ['class'=>'form-control', 'placeholder'=>'Digite nome do projeto']) }}
		{{ Form::button('Buscar <i class="fa fa-search"></i>', ['class'=>'btn btn-info', 'type'=>'submit']) }}
		{{ Form::close() }}
	</div>
</div>
<!-- /.row -->
<div class="col-md-12">
	
	 @include('partials.site.notifications')
	@if($projects->count() > 0)
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped">
			<tr>
				<th>Nome</th>
				<th>Produtor</th>
				<th>Data de criação</th>
				<th>Visualizar</th>
				<th>Aprovar</th>
				<!-- <th>Apagar</th> -->
				
			</tr>
			@foreach($projects as $project)
				<tr>
					
					<td>{{ $project->name }}</td>
					<td>{{ $project->user->name }}</td>
					<td>{{ Helper::ConverterBR($project->created_at) }} às {{ Helper::Hora($project->created_at) }}</td>
				
					
					<td><a class="btn btn-primary" href="{{ route('admin.projetos.show', ['id'=>$project->id]) }}"><i class="fa fa-search"></i></a></td>
					<td>
						{{ Form::open(['route'=>array('admin.projetos.aprovar',$project->id), 'class'=>'form-inline']) }}
						{{ Form::checkbox('status', '1', in_array('1', [$project->status]), ['class'=>'status_in','data-id'=>$project->id]) }}
						{{ Form::hidden('pid', $project->id) }}
						<a style="{{ $project->status == '0' ? 'display: inline;' : 'display: none' }}" id="modalLinkComment_{{ $project->id }}" data-toggle="modal" data-target="#modalComment_{{ $project->id }}" class="btn {{ $project->approval_comment != '' ? 'btn-success' : 'btn-info' }} comment_modal_link"><i class="fa fa-comment"></i></a>
						<span style="display: none;" class="loader_admin"><svg width='40px' height='40px' xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" class="uil-ripple"><rect x="0" y="0" width="100" height="100" fill="none" class="bk"></rect><g> <animate attributeName="opacity" dur="2s" repeatCount="indefinite" begin="0s" keyTimes="0;0.33;1" values="1;1;0"></animate><circle cx="50" cy="50" r="40" stroke="#ed4700" fill="none" stroke-width="6" stroke-linecap="round"><animate attributeName="r" dur="2s" repeatCount="indefinite" begin="0s" keyTimes="0;0.33;1" values="0;22;44"></animate></circle></g><g><animate attributeName="opacity" dur="2s" repeatCount="indefinite" begin="1s" keyTimes="0;0.33;1" values="1;1;0"></animate><circle cx="50" cy="50" r="40" stroke="#bfbfbf" fill="none" stroke-width="6" stroke-linecap="round"><animate attributeName="r" dur="2s" repeatCount="indefinite" begin="1s" keyTimes="0;0.33;1" values="0;22;44"></animate></circle></g></svg></span>
						{{ Form::close() }}
						
						<!-- Modal -->
						<div id="modalComment_{{ $project->id }}" class="modal fade" role="dialog">
						  <div class="modal-dialog">

						    <!-- Modal content-->
						    <div class="modal-content">
						      <div class="modal-header">
						        <button type="button" class="close" data-dismiss="modal">&times;</button>
						        <h4 class="modal-title">Comente sobre ão aprovação deste projeto</h4>
						        <p>{{ $project->name }}</p>
						      </div>
						      <div class="modal-body">
						        {{ Form::open(['route'=>array('admin.projetos.justifica', $project->id)]) }}
						        <div class="form-group">
						        	{{ Form::textarea('approval_comment', $project->approval_comment, ['class'=>'form-control']) }}

						        </div>
						        <div class="forr-group">
						        	{{ Form::button('Enviar <i class="fa fa-arrow-right"></i>', ['class'=>'btn btn-primary', 'type'=>'submit']) }}
						        </div>
						        {{ Form::close() }}
						      </div>
						      <div class="modal-footer">
						        <button type="button" class="btn btn-default" data-dismiss="modal">fechar</button>
						      </div>
						    </div>

						  </div>
						</div>

					</td>
					<!-- <td>
						{{ Form::open(['route'=>array('admin.projetos.destroy', 'id'=>$project->id), 'method'=>'delete']) }}
						<button class="btn btn-danger" type="submit">
								                <i class="fa fa-trash"></i>
								            </button>
						
						{{ Form::close() }}
					</td> -->
				</tr>
			@endforeach
		</table>
		{{ $projects->appends($_GET)->links() }}
	</div>
	@else
	<div class="alert alert-warning">
		<p><i class="fa fa-marker"></i> Ainda não temos conteúdo para esta área</p>
	</div>
	@endif
</div>
@stop

app/views/admin/projects/show.blade.php
@extends('layouts.admin')
@section('content')
<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Projeto <small>({{ $project->name }})</small>
        </h1>
    </div>
</div>
<!-- /.row -->
<div class="row">
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-12">
				<h2>Produtor</h2>
				<p><strong>Nome: </strong>{{ $project->user->name }}</p>
				<p><strong>Email: </strong>{{ $project->user->email }}</p>
				<p><strong>Localização: </strong>{{ $project->user->userdata->city->name or null }} - {{ $project->user->userdata->city->state->uf or null }}</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<h2>Informações</h2>
				<p><strong>Descrição: </strong>{{ $project->description }}</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<h2>Metas</h2>
				@foreach($project->objectives as $k => $objective)
					<p>{{ $k+1 }}. {{ $objective->name }}</p>
				@endforeach
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<h2>Recompensas</h2>
				@foreach($project->rewards as $k => $reward)
					<p>{{ $k+1 }}. {{ $reward->title }}</p>
				@endforeach
			</div>
		</div>
		
	</div>
	<div class="col-md-4">
		<img src="{{ $project->getImageSrc() }}" alt="">
	</div>
</div>

@stop