app/routes.php
<?php
# Site /estaticas

//Route::get('sub', 'SubscriptionsController@showSubCount');
Route::get('/',['as'=>'home','uses'=>'SiteController@index']);
Route::get('como-functiona', ['as'=>'about', 'uses'=>'SiteController@about']);
Route::get('perguntas-frequentes', ['as'=>'faq', 'uses'=>'SiteController@faq']);
Route::get('termos-de-uso', ['as'=>'terms', 'uses'=>'SiteController@terms']);
Route::get('contato', ['as'=>'get.contact', 'uses'=>'SiteController@getContact']);
Route::post('contato', ['as'=>'post.contact', 'uses'=>'SiteController@postContact']);
Route::post('webhooks',['as'=>'webhooks','uses'=>'SiteController@webhooks']);

# Cadastro
Route::get('cadastro',['before'=>'already.logged','as'=>'auth.register', 'uses'=>'AuthController@register']);
Route::post('cadastro',['as'=>'auth.post.register', 'uses'=>'AuthController@postRegister']);
# Testedecriação de conta
Route::get('criar-conta/{user_id}/teste/{project_id}', 'SubscriptionsController@createAccount');

# Newslleters
Route::post('newsletters', ['as'=>'newsletter.store', 'uses'=>'NewslettersController@store']);
# Login
Route::get('login',['before'=>'already.logged','as'=>'auth.login', 'uses'=>'AuthController@login']);
Route::post('login',['as'=>'auth.post.login', 'uses'=>'AuthController@postLogin']);
# BUscas
Route::get('buscar',['as'=>'main.search', 'uses'=>'ProjectsController@search']);
# Passwords
Route::get('password/reset', ['uses' => 'PasswordController@remind',  'as' => 'password.remind']);
Route::post('password/reset', ['uses' => 'PasswordController@request', 'as' => 'password.request']);
Route::get('password/reset/{token}', ['uses' => 'PasswordController@reset', 'as' => 'password.reset']);
Route::post('password/reset/{token}', ['uses' => 'PasswordController@update', 'as' => 'password.update']);

# Projetos
Route::get('projetos',['as'=>'projects.index', 'uses'=>'ProjectsController@indexSite']);
Route::get('projeto/{slug}',['as'=>'project.show', 'uses'=>'ProjectsController@showSite']);

# Categorias
Route::get('projetos/{slug_cat}',['as'=>'category.show', 'uses'=>'ProjectsController@indexSite']);
# Buscas
Route::post('city/search', ['as'=>'city.search', 'uses'=>'CitiesController@searchByState']);
Route::post('city/search/name', ['as'=>'city.search.name', 'uses'=>'CitiesController@searchByStateName']);

	# Pratocinar / Kart
Route::group(['before'=>'auth|force.ssl'],function(){
	Route::get('projeto/{slug}/patrocinar',['as'=>'project.subscribe', 'uses'=>'SubscriptionsController@getSubscribe']);
	Route::post('projeto/{slug}/patrocinar',['as'=>'project.payment.subscribe', 'uses'=>'SubscriptionsController@paymentSubscribe']);

	Route::get('projeto/{slug}/patrocinar/checkout',['as'=>'project.subscribe.checkout', 'uses'=>'SubscriptionsController@getSubscribeCheckout']);
	Route::post('projeto/{slug}/patrocinar/checkout',['as'=>'project.post.subscribe', 'uses'=>'SubscriptionsController@postSubscribe']);
});

# Accounts
Route::group(['prefix'=>'minha-conta','before'=>'auth'],function(){
	# Tipagem
	Route::get('patrocinador', ['before'=>'already.producer','as'=>'user.account.sponsor', 'uses'=>'UsersController@profileSponsor']);
	Route::get('produtor', ['before'=>'has.producer', 'as'=>'user.account.producer', 'uses'=>'SubscriptionsController@profileProducer']);

	#Produtor
	Route::get('produtor/verificacao', ['as'=>'producer.create', 'uses'=>'UsersController@createProducer']);
	Route::post('produtor/verificacao', ['as'=>'producer.store', 'uses'=>'SubscriptionsController@createAccount']);
	// Enviando a verificação ao IUGU
	Route::get('produtor/{pid}/verificacao', ['as'=>'sending.verification', 'uses'=>'SubscriptionsController@sendindVerification']);

	# Update de senha
	Route::post('salvar/nova/senha',['as'=>'user.update.password', 'uses'=>'PasswordController@updatePass']);

	#Updae userdata
	Route::post('salvar/dados/usuario',['as'=>'user.update.userdata','uses'=>'UsersController@updateUserdata']);
	# Upload de imagem
	Route::post('image/upload', ['as'=>'user.upload.photo','uses'=>'UsersController@uploadImage']);

	# Projetos
	Route::get('projeto',['before'=>'has.producer','as'=>'projects.create', 'uses'=>'ProjectsController@createSite']);
	Route::post('projeto', ['before'=>'has.producer','as'=>'projects.store', 'uses'=>'ProjectsController@storeSite']);

	Route::group(['before'=>'my.project|has.producer', 'prefix'=>'projeto/{slug}'], function(){
		Route::get('editar',['as'=>'projects.edit', 'uses'=>'ProjectsController@editSite']);
		Route::post('editar', ['as'=>'projects.update', 'uses'=>'ProjectsController@updateSite']);

		# Projeto single(área admin)
		Route::get('/',['as'=>'projects.account.show', 'uses'=>'ProjectsController@accountShow']);

		# Criação de metas e recompensas
		Route::get('metas',['as'=>'project.objective.create', 'uses'=>'ProjectsController@objectiveCreate']);
		Route::post('metas',['as'=>'project.objective.store', 'uses'=>'ProjectsController@objectiveStore']);
		Route::delete('metas/{objective_id}',['as'=>'project.objective.delete', 'uses'=>'ProjectsController@objectiveDelete']);
		Route::get('recompensas',['as'=>'project.reward.create', 'uses'=>'ProjectsController@rewardCreate']);
		Route::post('recompensas',['as'=>'project.reward.store', 'uses'=>'SubscriptionsController@rewardStore']);
                Route::delete('recompensas/{reward_id}',['as'=>'project.reward.delete', 'uses'=>'ProjectsController@rewardDelete']);
	});

	# Cancelar subscriptiom
	Route::post('cancelar/{subscription_id}',['as'=>'subscription.cancel','uses'=>'SubscriptionsController@cancel']);
	#Logout
	Route::get('logout',['as'=>'user.logout', 'uses'=>'AuthController@logout']);

});
# Admin
Route::get('admin',['before'=>'already.logged.admin','as'=>'admin.login', 'uses'=>'AdminController@login']);
Route::post('admin/login',['as'=>'admin.post.login', 'uses'=>'AdminController@postLogin']);
Route::get('admin/logout',['as'=>'admin.logout', 'uses'=>'AdminController@logout']);

Route::group(['prefix'=>'admin', 'before'=>'auth|admin', 'namespace' => 'Admin'], function(){
    
    Route::resource('projetos', 'ProjectsController');
    Route::post('projeto/{id}/aprovar', ['as'=>'admin.projetos.aprovar', 'uses'=>'ProjectsController@aprovar']);
    Route::post('projeto/{id}/justifica', ['as'=>'admin.projetos.justifica', 'uses'=>'ProjectsController@justifica']);
    
    Route::resource('usuarios', 'UsersController');
    Route::post('usuario/{id}/ativacao', ['as'=>'admin.user.deactivate', 'uses'=>'UsersController@deactivate']);
        
    Route::resource('newsletters', 'NewslettersController');
    Route::post('news/download', ['as'=>'admin.newsletters.download', 'uses'=>'NewslettersController@download']);
    
    Route::resource('patrocinios', 'SubscriptionsController');
    Route::get('dashboard', ['as'=>'admin.dashboard.index', 'uses'=>'DashboardController@index']);
}); 

app/controllers/Admin/DashboardController.php
<?php

namespace Admin;

use \View;
use \Input;
use \DB;

class DashboardController extends \BaseController 
{
    public function index()
    {
        $to = Input::get('to',date('Y-m-d'));
        $from = Input::get('from',date('Y-m-d', strtotime($to.' -1 months')));
        
        $subscriptions = [
            'per_project' => $this->getSubsQuery($from,$to)
                ->select(DB::raw('count(*) as count, (SELECT name FROM projects as p WHERE p.id = project_id) as project_name, project_id'))
                ->groupBy('project_id')
                ->orderBy('project_id', 'asc')
                ->get()
            ,
            'type' => $this->getSubsQuery($from,$to)
                ->select(DB::raw("count(1) as value, case type when '1' then 'Cartão' when '2' then 'Boleto' else 'Cartão' end as label, '#01a8fe' as color, '#01a8fe' as highlight "))
                ->groupBy('type')
                ->get()
            ,
            'count' => $this->getSubsQuery($from,$to)->count(),
            'pending' => $this->getSubsQuery($from,$to)->where('status','0')->count(),
            'sum' => $this->getSubsQuery($from,$to)->sum('amount'),
        ];
        
        $users = [
            'count' => $this->getUsersQuery($from,$to)->count(),
            'progression' => $this->getUsersQuery($from,$to)->select(DB::raw('count(*) as user_count, date(created_at)'))->groupBy('date(created_at)')->orderBy('created_at', 'asc')->get()
        ];
                
	return View::make('admin2.dashboard.index', compact('from','to','subscriptions','users'));
    }
    
    private function getSubsQuery($from,$to) {
        return DB::table('subscriptions')
            ->whereRaw('date(created_at) >= ? AND date(created_at) <= ?',[$from,$to])
        ;
    }
    
    private function getUsersQuery($from,$to) {
        return DB::table('users')
            ->whereRaw('date(created_at) >= ? AND date(created_at) <= ?',[$from,$to])
        ;
    }
    
}

app/views/admin2/dashboard/index.blade.php
@extends('layouts.admin2')
@section('content')

<div class="row">
    <div class="col-sm-12">
        <div class="page-title">
            <div class="pull-left">
                <h1>Dashboard</h1>
            </div>
            
            <div class="pull-right">
                <form class="form-inline">
                    <input type="date" name="from" class="form-control" value="{{ $from }}">
                    <input type="date" name="to" class="form-control" value="{{ $to }}">
                    <button type="submit" class="btn btn-default">Filtrar</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>
<div style="margin-bottom: 25px;"></div>

<div class="row">
    <div class="col-md-12">
        @include('admin2.partials.notifications')
    </div>
</div>

<div class="row">
    <div class="col-lg-4">
        <div class="widget-box clearfix">
            <div class="pull-left">
                <h4>Novos Usuários</h4>
                <h2>{{ $users['count'] }}</h2>
            </div>
            <div class="text-right">
                <span id="sparkline8"></span>
            </div>
        </div>
    </div>
    <div class="col-lg-8">
        <div class="row">
            <div class="col-md-4">
                <div class="widget-box clearfix">
                    <div>
                        <h4>Novos patrocinios</h4>
                        <h2>{{ $subscriptions['count'] }} <i class="fa fa-plus pull-right"></i></h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="widget-box clearfix">
                    <div>
                        <h4>Total de vendas</h4>
                        <h2>R${{ Helper::Monetize($subscriptions['sum']/100) }} <i class="fa fa-shopping-cart pull-right"></i></h2>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="widget-box clearfix">
                    <div>
                        <h4>Assinaturas Pendentes</h4>
                        <h2>{{ $subscriptions['pending'] }} <i class="fa fa-tasks pull-right"></i></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-6">
        <div class="panel panel-card recent-activites">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">Divisão de Assinaturas por Projeto</h4>
            </div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th width="10">%</th>
                            <th width="10"></th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php $total_projects = count($subscriptions['per_project']) ?>
                            @foreach($subscriptions['per_project'] as $s)
                            <tr>
                                <td>{{ $s->project_name }}</td>
                                <td><div class="sparkline" data-total="{{ $total_projects }}" data-share="{{ $s->count }}"></div></td>
                                <td class="text-center"><a class="pull-left btn btn-default btn-xs" title="Editar" href="{{ route('admin.projetos.edit', $s->project_id) }}"><i class="fa fa-pencil"></i></a> </td>
                            </tr>
                            @endforeach
                        </tbody>
                </table>
            </div>
        </div><!-- End .panel --> 
    </div>
    <div class="col-sm-6">
        <div class="panel panel-card recent-activites">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">Meios de Pagamento</h4>
            </div>
            <div class="panel-body">
                <div>
                    <canvas id="doughnutChart" height="140"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>



@stop
@section('footer')
    @parent
    {{ HTML::script('admin/js/jquery.sparkline.min.js') }}
    {{ HTML::script('admin/js/morris_chart/raphael-2.1.0.min.js') }}
    {{ HTML::script('admin/js/morris_chart/morris.js') }}
    {{ HTML::script('admin/js/chartjs/Chart.min.js') }}
    <script>
        $("#sparkline8").sparkline([{{ join(',',array_pluck($users['progression'],'user_count')) }}], {
            type: 'bar',
            barWidth: 4,
            height: '40px',
            barColor: '#01a8fe',
            negBarColor: '#c6c6c6'
        });
        
        $(".sparkline").each(function(){
            var el = $(this);
            el.sparkline([el.data('share'),el.data('total')], {
                type: 'pie',
                sliceColors: ['#01a8fe', '#ddd']
            });
        });
        
    var doughnutOptions = {
        segmentShowStroke: true,
        segmentStrokeColor: "#fff",
        segmentStrokeWidth: 2,
        percentageInnerCutout: 45, // This is 0 for Pie charts
        animationSteps: 100,
        animationEasing: "easeOutBounce",
        animateRotate: true,
        animateScale: false,
        responsive: true
    };
        
        var ctx = document.getElementById("doughnutChart").getContext("2d");
        var myNewChart = new Chart(ctx).Doughnut({{json_encode($subscriptions['type']) }}, doughnutOptions);
    </script>
@stop