app/routes.php
<?php
# Site /estaticas

//Route::get('sub', 'SubscriptionsController@showSubCount');
Route::get('/',['as'=>'home','uses'=>'SiteController@index']);
Route::get('como-functiona', ['as'=>'about', 'uses'=>'SiteController@about']);
Route::get('perguntas-frequentes', ['as'=>'faq', 'uses'=>'SiteController@faq']);
Route::get('termos-de-uso', ['as'=>'terms', 'uses'=>'SiteController@terms']);
Route::get('contato', ['as'=>'get.contact', 'uses'=>'SiteController@getContact']);
Route::post('contato', ['as'=>'post.contact', 'uses'=>'SiteController@postContact']);
Route::post('webhooks',['as'=>'webhooks','uses'=>'SiteController@webhooks']);

# Cadastro
Route::get('cadastro',['before'=>'already.logged','as'=>'auth.register', 'uses'=>'AuthController@register']);
Route::post('cadastro',['as'=>'auth.post.register', 'uses'=>'AuthController@postRegister']);
# Testedecriação de conta
Route::get('criar-conta/{user_id}/teste/{project_id}', 'SubscriptionsController@createAccount');

# Newslleters
Route::post('newsletters', ['as'=>'newsletter.store', 'uses'=>'NewslettersController@store']);
# Login
Route::get('login',['before'=>'already.logged','as'=>'auth.login', 'uses'=>'AuthController@login']);
Route::post('login',['as'=>'auth.post.login', 'uses'=>'AuthController@postLogin']);
# BUscas
Route::get('buscar',['as'=>'main.search', 'uses'=>'ProjectsController@search']);
# Passwords
Route::get('password/reset', ['uses' => 'PasswordController@remind',  'as' => 'password.remind']);
Route::post('password/reset', ['uses' => 'PasswordController@request', 'as' => 'password.request']);
Route::get('password/reset/{token}', ['uses' => 'PasswordController@reset', 'as' => 'password.reset']);
Route::post('password/reset/{token}', ['uses' => 'PasswordController@update', 'as' => 'password.update']);

# Projetos
Route::get('projetos',['as'=>'projects.index', 'uses'=>'ProjectsController@indexSite']);
Route::get('projeto/{slug}',['as'=>'project.show', 'uses'=>'ProjectsController@showSite']);

# Categorias
Route::get('projetos/{slug_cat}',['as'=>'category.show', 'uses'=>'ProjectsController@indexSite']);
# Buscas
Route::post('city/search', ['as'=>'city.search', 'uses'=>'CitiesController@searchByState']);
Route::post('city/search/name', ['as'=>'city.search.name', 'uses'=>'CitiesController@searchByStateName']);

	# Pratocinar / Kart
Route::group(['before'=>'auth|force.ssl'],function(){
	Route::get('projeto/{slug}/patrocinar',['as'=>'project.subscribe', 'uses'=>'SubscriptionsController@getSubscribe']);
	Route::post('projeto/{slug}/patrocinar',['as'=>'project.payment.subscribe', 'uses'=>'SubscriptionsController@paymentSubscribe']);

	Route::get('projeto/{slug}/patrocinar/checkout',['as'=>'project.subscribe.checkout', 'uses'=>'SubscriptionsController@getSubscribeCheckout']);
	Route::post('projeto/{slug}/patrocinar/checkout',['as'=>'project.post.subscribe', 'uses'=>'SubscriptionsController@postSubscribe']);
});

# Accounts
Route::group(['prefix'=>'minha-conta','before'=>'auth'],function(){
	# Tipagem
	Route::get('patrocinador', ['before'=>'already.producer','as'=>'user.account.sponsor', 'uses'=>'UsersController@profileSponsor']);
	Route::get('produtor', ['before'=>'has.producer', 'as'=>'user.account.producer', 'uses'=>'SubscriptionsController@profileProducer']);

	#Produtor
	Route::get('produtor/verificacao', ['as'=>'producer.create', 'uses'=>'UsersController@createProducer']);
	Route::post('produtor/verificacao', ['as'=>'producer.store', 'uses'=>'SubscriptionsController@createAccount']);
	// Enviando a verificação ao IUGU
	Route::get('produtor/{pid}/verificacao', ['as'=>'sending.verification', 'uses'=>'SubscriptionsController@sendindVerification']);

	# Update de senha
	Route::post('salvar/nova/senha',['as'=>'user.update.password', 'uses'=>'PasswordController@updatePass']);

	#Updae userdata
	Route::post('salvar/dados/usuario',['as'=>'user.update.userdata','uses'=>'UsersController@updateUserdata']);
	# Upload de imagem
	Route::post('image/upload', ['as'=>'user.upload.photo','uses'=>'UsersController@uploadImage']);

	# Projetos
	Route::get('projeto',['before'=>'has.producer','as'=>'projects.create', 'uses'=>'ProjectsController@createSite']);
	Route::post('projeto', ['before'=>'has.producer','as'=>'projects.store', 'uses'=>'ProjectsController@storeSite']);

	Route::group(['before'=>'my.project|has.producer', 'prefix'=>'projeto/{slug}'], function(){
		Route::get('editar',['as'=>'projects.edit', 'uses'=>'ProjectsController@editSite']);
		Route::post('editar', ['as'=>'projects.update', 'uses'=>'ProjectsController@updateSite']);

		# Projeto single(área admin)
		Route::get('/',['as'=>'projects.account.show', 'uses'=>'ProjectsController@accountShow']);

		# Criação de metas e recompensas
		Route::get('metas',['as'=>'project.objective.create', 'uses'=>'ProjectsController@objectiveCreate']);
		Route::post('metas',['as'=>'project.objective.store', 'uses'=>'ProjectsController@objectiveStore']);
		Route::delete('metas/{objective_id}',['as'=>'project.objective.delete', 'uses'=>'ProjectsController@objectiveDelete']);
		Route::get('recompensas',['as'=>'project.reward.create', 'uses'=>'ProjectsController@rewardCreate']);
		Route::post('recompensas',['as'=>'project.reward.store', 'uses'=>'SubscriptionsController@rewardStore']);
                Route::delete('recompensas/{reward_id}',['as'=>'project.reward.delete', 'uses'=>'ProjectsController@rewardDelete']);
	});

	# Cancelar subscriptiom
	Route::post('cancelar/{subscription_id}',['as'=>'subscription.cancel','uses'=>'SubscriptionsController@cancel']);
	#Logout
	Route::get('logout',['as'=>'user.logout', 'uses'=>'AuthController@logout']);

});
# Admin
Route::get('admin',['before'=>'already.logged.admin','as'=>'admin.login', 'uses'=>'AdminController@login']);
Route::post('admin/login',['as'=>'admin.post.login', 'uses'=>'AdminController@postLogin']);
Route::get('admin/logout',['as'=>'admin.logout', 'uses'=>'AdminController@logout']);

Route::group(['prefix'=>'admin', 'before'=>'auth|admin', 'namespace' => 'Admin'], function(){
    
    Route::resource('projetos', 'ProjectsController');
    Route::post('projeto/{id}/aprovar', ['as'=>'admin.projetos.aprovar', 'uses'=>'ProjectsController@aprovar']);
    Route::post('projeto/{id}/justifica', ['as'=>'admin.projetos.justifica', 'uses'=>'ProjectsController@justifica']);
    
    Route::resource('usuarios', 'UsersController');
    Route::post('usuario/{id}/ativacao', ['as'=>'admin.user.deactivate', 'uses'=>'UsersController@deactivate']);
        
    Route::resource('newsletters', 'NewslettersController');
    Route::post('news/download', ['as'=>'admin.newsletters.download', 'uses'=>'NewslettersController@download']);
    
    Route::resource('patrocinios', 'SubscriptionsController');
    Route::get('dashboard', ['as'=>'admin.dashboard.index', 'uses'=>'DashboardController@index']);
}); 

app/views/admin2/partials/notifications.blade.php
@if(Session::has('success'))
    <div class="alert alert-success">
        <i class="icon icon-arrows-circle-check"></i> {{ Session::get('success')  }}
    </div> 
@endif

@if(Session::has('warning'))
    <div class="alert alert-warning">
        <i class="icon icon-arrows-circle-check"></i> {{ Session::get('warning')  }}
    </div> 
@endif

@if(Session::has('error'))
    <div class="alert alert-danger">
        <i class="fa fa-exclamation-circle"></i> {{ Session::get('error')  }}
    </div> 
@endif

app/views/admin2/partials/sidenav.blade.php
<nav class="navbar-aside navbar-static-side" role="navigation">
    <div class="sidebar-collapse nano">
        <div class="nano-content">
            <ul class="nav metismenu" id="side-menu">
                <li class="nav-header">
                    <div class="dropdown side-profile text-left"> 
                        <span style="display: block;">
                            <img src="{{ Helper::getUserThumbnail(Sentry::getUser()->id) }}" class="img-circle" width="40">
                        </span>
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear" style="display: block;">
                                <span class="block m-t-xs">
                                    <strong class="font-bold">{{ Sentry::getUser()->name }}  
                                        <b class="caret"></b></strong>
                                </span>
                            </span>
                        </a>
                        <ul class="dropdown-menu animated fadeInRight m-t-xs">
                            <li><a href="{{ route('admin.usuarios.edit', Sentry::getUser()->id) }}"><i class="fa fa-user"></i>Meu Perfil</a></li>
                            <li class="divider"></li>
                            <li><a href="{{route('admin.logout')}}"><i class="fa fa-key"></i>Sair</a></li>
                        </ul>
                    </div>
                </li>
                <li class="{{ Helper::activeMenu('admin.dashboard.index') }}">
                    <a href="{{ route('admin.dashboard.index') }}"><i class="fa fa-th-large"></i>Dashboard</a>
                </li>
                <li class="{{ Helper::activeMenu('admin.projetos.index') }}">
                    <a href="{{ route('admin.projetos.index') }}"><i class="fa fa-laptop"></i>Projetos</a>
                </li>
                <li class="{{ Helper::activeMenu('admin.usuarios.index') }}">
                    <a href="{{ route('admin.usuarios.index') }}"><i class="fa fa-users"></i>Usuários</a>
                </li>
                <li class="{{ Helper::activeMenu('admin.newsletters.index') }}">
                    <a href="{{ route('admin.newsletters.index') }}"><i class="fa fa-envelope"></i> Newsletters</a>
                </li>
                <li class="{{ Helper::activeMenu('admin.patrocinios.index') }}">
                    <a href="{{ route('admin.patrocinios.index') }}"><i class="fa fa-money"></i> Patrocínios</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/admin2/partials/topnav.blade.php
<nav class="navbar navbar-default yamm navbar-fixed-top">
    <div class="container-fluid">
        <button type="button" class="navbar-minimalize minimalize-styl-2  pull-left "><i class="fa fa-bars"></i></button>
        <!--<span class="search-icon"><i class="fa fa-search"></i></span>
        <div class="search" style="display: none;">
            <form role="form">
                <input type="text" class="form-control" autocomplete="off" placeholder="Write something and press enter">
                <span class="search-close"><i class="fa fa-times"></i></span>
            </form>
        </div>-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('admin.projetos.index') }}">Bepartus</a>
        </div>
        <?php /*
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle button-wave" data-toggle="dropdown" aria-expanded="true">Mega Menu<span class="caret"></span></a>
                    <ul class="dropdown-menu mega-dropdown-menu" style="width: 900px;">
                        <li>
                            <div class="yamm-content">
                                <div class="row ">
                                    <div class="col-sm-3 ">

                                        <h3 class="yamm-category">Layout</h3>
                                        <ul class="list-unstyled ">
                                            <li><a href="">Admin style 1</a></li>
                                            <li><a href="">Admin style 2</a></li>
                                            <li><a href="">Admin style 3</a></li>
                                            <li><a href="">Admin style 4</a></li>   
                                        </ul>


                                    </div>
                                    <div class="col-sm-3">

                                        <h3 class="yamm-category">Ui Kit</h3>
                                        <ul class="list-unstyled ">
                                            <li><a href="">Typography</a></li>
                                            <li><a href="">Buttons</a></li>
                                            <li><a href="">Font Awesome</a></li>
                                            <li><a href="">Tabs & Alerts</a></li>
                                        </ul>


                                    </div>
                                    <div class="col-sm-3">

                                        <h3 class="yamm-category">Analytics</h3>
                                        <ul class="list-unstyled ">
                                            <li><a href="">Flot</a></li>
                                            <li><a href="">Sparklines</a></li>
                                            <li><a href="">Morris</a></li>
                                            <li><a href="">Chart Js</a></li>
                                        </ul>


                                    </div>
                                    <div class="col-sm-3">
                                        <h3 class="yamm-category">Architecto</h3>
                                        <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle button-wave" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right navbar-top-drops">
                <li class="dropdown"><a href="#" class="dropdown-toggle button-wave" data-toggle="dropdown"><i class="fa fa-envelope"></i> <span class="badge badge-xs badge-info">6</span></a>

                    <ul class="dropdown-menu dropdown-lg">
                        <li class="notify-title">
                            3 New messages 
                        </li>
                        <li class="clearfix">
                            <a href="#">
                                <span class="pull-left">
                                    <img src="images/avtar-1.jpg" alt="" class="img-circle" width="30">
                                </span>
                                <span class="block">
                                    John Doe
                                </span>
                                <span class="media-body">
                                    Lorem ipsum dolor sit amet
                                    <em>28 minutes ago</em>
                                </span>
                            </a>
                        </li>
                        <li class="clearfix">
                            <a href="#">
                                <span class="pull-left">
                                    <img src="images/avtar-2.jpg" alt="" class="img-circle" width="30">
                                </span>
                                <span class="block">
                                    John Doe
                                </span>
                                <span class="media-body">
                                    Lorem ipsum dolor sit amet
                                    <em>28 minutes ago</em>
                                </span>
                            </a>
                        </li>
                        <li class="clearfix">
                            <a href="#">
                                <span class="pull-left">
                                    <img src="images/avtar-3.jpg" alt="" class="img-circle" width="30">
                                </span>
                                <span class="block">
                                    John Doe
                                </span>
                                <span class="media-body">
                                    Lorem ipsum dolor sit amet
                                    <em>28 minutes ago</em>
                                </span>
                            </a>
                        </li>
                        <li class="read-more"><a href="#">View All Messages <i class="fa fa-angle-right"></i></a></li>
                    </ul>
                </li>
                <li class="dropdown"><a href="#" class="dropdown-toggle button-wave" data-toggle="dropdown"><i class="fa fa-bell"></i> <span class="badge badge-xs badge-warning">6</span></a>

                    <ul class="dropdown-menu dropdown-lg">
                        <li class="notify-title">
                            3 New messages 
                        </li>
                        <li class="clearfix">
                            <a href="#">
                                <span class="pull-left">
                                    <i class="fa fa-envelope"></i>
                                </span>

                                <span class="media-body">
                                    15 New Messages
                                    <em>20 Minutes ago</em>
                                </span>
                            </a>
                        </li>
                        <li class="clearfix">
                            <a href="#">
                                <span class="pull-left">
                                    <i class="fa fa-twitter"></i>
                                </span>

                                <span class="media-body">
                                    13 New Followers
                                    <em>2 hours ago</em>
                                </span>
                            </a>
                        </li>
                        <li class="clearfix">
                            <a href="#">
                                <span class="pull-left">
                                    <i class="fa fa-download"></i>
                                </span>

                                <span class="media-body">
                                    Download complete
                                    <em>2 hours ago</em>
                                </span>
                            </a>
                        </li>
                        <li class="read-more"><a href="#">View All Alerts <i class="fa fa-angle-right"></i></a></li>
                    </ul>
                </li>

            </ul>
        </div><!--/.nav-collapse --> */ ?>
    </div><!--/.container-fluid -->
</nav>